version: '3.8'

services:
  webapp:
    build: .
    container_name: rental-app
    restart: unless-stopped
    ports:
      - "8080:9090"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Xmx512m -XX:+UseG1GC
      - CATALINA_OPTS=-Dfile.encoding=UTF-8
      - CATALINA_PORT=9090
    volumes:
      - tomcat_logs:/usr/local/tomcat/logs
      - tomcat_temp:/usr/local/tomcat/temp
      - app_uploads:/usr/local/tomcat/webapps/ROOT/uploads
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - coolify

volumes:
  tomcat_logs:
  tomcat_temp:
  app_uploads:
  # db_data:

networks:
  coolify:
    external: true
