version: '3.8'

services:
  webapp:
    build: .
    container_name: rental-app
    restart: unless-stopped
    ports:
      - "9090:9090"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx1024m -Xms512m
      - CATALINA_OPTS=-Dfile.encoding=UTF-8
      - CATALINA_PORT=9090
    volumes:
      - tomcat_logs:/usr/local/tomcat/logs
      - tomcat_temp:/usr/local/tomcat/temp
      - app_uploads:/usr/local/tomcat/webapps/ROOT/uploads
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    labels:
      - traefik.enable=true
      - traefik.http.routers.staynow.rule=Host(`staynow.tinkering.vn`)
      - traefik.http.routers.staynow.entrypoints=https
      - traefik.http.routers.staynow.tls.certresolver=letsencrypt
      - traefik.http.services.staynow.loadbalancer.server.port=9090
      - traefik.http.services.staynow.loadbalancer.server.scheme=http
      
      # WebSocket upgrade headers middleware
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=upgrade
      - traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket

      # WebSocket route for /chat
      - traefik.http.routers.chat-edu-center.rule=Host(`staynow.tinkering.vn`) && PathPrefix(`/chat`)
      - traefik.http.routers.chat-edu-center.entrypoints=https
      - traefik.http.routers.chat-edu-center.tls.certresolver=letsencrypt
      - traefik.http.routers.chat-edu-center.service=staynow
      - traefik.http.routers.chat-edu-center.middlewares=websocket-headers

volumes:
  tomcat_logs:
  tomcat_temp:
  app_uploads:
  # db_data:

networks:
  app-network:
    driver: bridge
